name    'puppetlabs-dnsclient'
version '3.0.0'
source 'git://github.com/puppetlabs/puppet-dnsclient.git'
author 'puppetlabs'
license 'Apache License, Version 2.0'
summary 'Manage resolver'
description 'Manage a dns client's resolver'
project_page 'https://github.com/puppetlabs/puppet-dnsclient/'
